### ISSUE TITLE
Prior CSVs are not available in the stable channel.

### ISSUE THREAD

**Issue by kaovilai** [backube/volsync#648]
Similar to https://github.com/minio/operator/issues/1299
Our team made a similar mistake and resolved this working with CLOUDDST to prune and republish https://issues.redhat.com/browse/CLOUDDST-15410

Your CSVs are not setting `.spec.replaces` thus breaking upgrade graphs which mean the upgrade button won't be visible in the web console.

https://redhat-internal.slack.com/archives/C3VS0LV41/p1662480128267119?thread_ts=1662475844.026329&cid=C3VS0LV41

```
~ master*
❯ oc get csv volsync-product.v0.6.0 -oyaml | grep replaces 

~ master*
❯ 
```

**Comment by kaovilai** [comment]
0.5.1 subscription would get constraints not satisfiable.

Removing existing subscription allows for new installation to proceed.

**Comment by tesshuflower** [comment]
Because of how OLM works, we're not going to try to fix this in the stable channel.

We can't always use replaces as we need to publish new .Y releases into new channels, and then if the "replaces" version isn't there, it doesn't work.

Going forward we are going to be creating `release-X.Y` channels for the releases - and in those channels, all versions of the release should be visible.  This will start with a `release-0.7` channel.

If a user just wants the latest, then they can continue using the `stable` channel.  But they won't be able to pick a specific older release in the channel.


In the meantime if someone wants a 0.5.x build they can use the `acm-2.6` channel.  Similarly for a 0.6.x build they can use the `acm-2.7 channel.

**Comment by kaovilai** [comment]
Just as a note, it is possible to work with team above to prune and "rewrite" the update graph if required.

You can use replaces and still publish new .Y releases into new channels. See what [was achieved](https://issues.redhat.com/browse/CLOUDDST-15410?focusedCommentId=20978820&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20978820)

But stated workarounds are acceptable imo.
